version: "3"
services:
        cas_web:
                build: ./WebServer/
                container_name: cas_web
                image: cas_web
                networks:
                        - cas
                restart: unless-stopped
        cas_proxy:
                build: ./Proxy/
                container_name: cas_proxy
                depends_on:
                        - cas_web
                networks:
                        - cas
                ports:
                        - 80:80
                        - 443:443
                restart: unless-stopped
networks:
        cas:
