# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestI4AAorario():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_i4AAorario(self):
    # Test name: I4AA - orario
    # Step # | name | target | value | comment
    # 1 | open | /orario/invite?invite=true |  | 
    self.driver.get("https://www.cpttrevano.ti.ch/orario/invite?invite=true")
    # 2 | setWindowSize | 1384x794 |  | 
    self.driver.set_window_size(1384, 794)
    # 3 | click | id=GInterface.Instances[0].Instances[0]_Combo1 |  | 
    self.driver.find_element(By.ID, "GInterface.Instances[0].Instances[0]_Combo1").click()
    # 4 | click | id=GInterface.Instances[1].Instances[1].bouton_Edit |  | 
    self.driver.find_element(By.ID, "GInterface.Instances[1].Instances[1].bouton_Edit").click()
    # 5 | type | id=GInterface.Instances[1].Instances[1].bouton_Edit | SAM D1AA | 
    self.driver.find_element(By.ID, "GInterface.Instances[1].Instances[1].bouton_Edit").send_keys("SAM D1AA")
    # 6 | click | css=#GInterface\.Instances\[1\]\.Instances\[1\]_0 > span |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#GInterface\\.Instances\\[1\\]\\.Instances\\[1\\]_0 > span").click()
    # 7 | click | id=GInterface.Instances[0].Instances[2].bouton_Bouton |  | 
    self.driver.find_element(By.ID, "GInterface.Instances[0].Instances[2].bouton_Bouton").click()
    # 8 | click | id=GInterface.Instances[0].Instances[2]_1 |  | 
    self.driver.find_element(By.ID, "GInterface.Instances[0].Instances[2]_1").click()
    # 9 | close |  |  |
    self.driver.close()

